apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ils-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reroils
        tier: frontend
    spec:
      containers:
      - name: reroils-app
        image: rero/reroils-app:latest
        imagePullPolicy: Always
        env:
        - name: PATH
          value: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/reroils/reroils/bin
        - name: GET_HOSTS_FROM
          value: dns
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: reroils-app
              key: worker-user
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: reroils-app
              key: worker-password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: reroils-app
              key: db-user
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: reroils-app
              key: db-name
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: reroils-app
              key: db-password
        - name: INVENIO_SEARCH_ELASTIC_HOSTS
          value: ils-indexer:$(ILS_INDEXER_SERVICE_PORT_API)
        - name: INVENIO_SQLALCHEMY_DATABASE_URI
          value: postgresql+psycopg2://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@ils-db:$(ILS_DB_SERVICE_PORT_DB)/$(POSTGRES_DB)
        - name: INVENIO_CELERY_BROKER_URL
          value: 'amqp://$(RABBITMQ_DEFAULT_USER):$(RABBITMQ_DEFAULT_PASS)@ils-worker:$(ILS_WORKER_SERVICE_PORT_WORKER)//'
        - name: INVENIO_CELERY_RESULT_BACKEND
          value: 'redis://ils-cache:$(ILS_CACHE_SERVICE_PORT_CACHE)/1'
        - name: INVENIO_CACHE_REDIS_URL
          value: 'redis://ils-cache:$(ILS_CACHE_SERVICE_PORT_CACHE)/1'
        - name: INVENIO_ACCOUNTS_SESSION_REDIS_URL
          value: 'redis://ils-cache:$(ILS_CACHE_SERVICE_PORT_CACHE)/0'
        - name: INVENIO_DB_VERSIONING
          value: '0'
        ports:
        - containerPort: 5000
        volumeMounts:
          - mountPath: /data
            name: ils-data
      volumes:
      - name: ils-data
        hostPath:
          path: /data/docker/reroils
